added helper for update order_status
h5law/epstore pull request #2
Opened 2022-07-13 03:26 UTC by Raphael-hub

2022-07-13 07:15 UTC, h5law requested changes
This still needs a lot of work - I am wondering if you are testing your code? Write a simple route and test your functions work with postman. Otherwise, how can you be sure they are doing what you think? You are also not exporting either of the functions at the bottom - they should be in the `orders` export object. I am here if you need me to help with any of the comments I have made.

2022-07-13 07:15 UTC, h5law commented on src/db/helpers.js
> +     throw new Error('Unable to find buyer');
`'Unable to find user for this order'` sounds a bit better - not super important though

2022-07-13 07:15 UTC, h5law commented on src/db/helpers.js
> +    const { updatedOrder } = await query(queryString);
object deconstruction only works for named keys in the object so this will run the query but return undefined - you need `{ rows }` if you are trying to deconstruct this.

2022-07-13 07:15 UTC, h5law commented on src/db/helpers.js
> +    'SELECT status FROM orders_products WHERE orders_products.order_id = $1 ', [order_id]
`orders_products.order_id` can be `order_id` there is only one table in the query so columns with the same name don't need to be clarified

2022-07-13 07:15 UTC, h5law commented on src/db/helpers.js
> +  if (products_status.filter(status=> status === 'shipped' || status === 'disputed').length < products_status.length) {
Here you are going to run into an error where if all the other products in an order are marked as disputed and the final one you mark from pending to shipped - the entire order will be marked shipped. Also `status` cannot be used as the name for the argument of this callback as it is the argument already passed into the function change it to `s` or something you will probably get an error

2022-07-13 07:15 UTC, h5law commented on src/db/helpers.js
> +  [status, order_id])
Here if you are having multiple queries depend on each other you should start a transaction like we talked about - use `getClient()` from `db/index.js` and `client.query('BEGIN')` to start put it all in the `try/catch` block.

2022-07-13 07:15 UTC, h5law commented on src/db/helpers.js
> +
Try and sort out your whitespace there is so many extra new lines and weird indentation - try and keep things as far left as possible, while sticking to correct indentation and minimise new lines when they are not needed

2022-07-13 07:21 UTC, h5law commented on src/db/helpers.js
> +const updateOrderProductStatus = async (order_id, product_id, status) => {
We should probably add an argument here `user_id, order_id, product_id, status` where `user_id` is the vendor and we should firstly check that the given `user_id` is the owner of the given `product_id`

2022-07-13 11:46 UTC, h5law commented on src/db/helpers.js
> +};
Yeah both should have arguments like `user_id, order_id, product_id, status` and `user_id, order_id, status` where `user_id` is the id of the vendor - so you will have to check against the products table that the user_id provided is the owner of the product_id

2022-07-13 20:25 UTC, h5law requested changes
Whitespace and indentation still need to be sorted out but this looks good - remember to test it too. You should look into what you are returning as well. Check the other helper functions that return similar things to the vendor - not the buyer who made the order. We would want to abstract things like the `user_id` and replace it with the `username`. Check the `getVendorOrders` function to see an example of this.

2022-07-13 20:25 UTC, h5law commented on src/db/helpers.js
> +      WHERE id = $2 AND user_id = $1 RETURNING  id',[user_id, order_id, status] );
It makes more sense to order them `[status, order_id, user_id]` and put the `$1..3` in order, just for easier readability

2022-07-13 20:25 UTC, h5law commented on src/db/helpers.js
>      }
After checking the vendor exists we should check that the user_id is also the owner of every product in the order - a vendor shouldn't be allowed to mark an entire order as shipped if they don't own all the items being ordered

2022-07-13 20:25 UTC, h5law commented on src/db/helpers.js
> +    }
Here we should check that the user_id (vendor's id) is the same user_id found in the product with the product_id we are trying to update - again they have to actually own the product to update its status

2022-07-13 20:25 UTC, h5law commented on src/db/helpers.js
> +      return await cancelOrder(user_id, order_id);
Instead use `cancelOrderProduct(buyer_id, order_id, product_id)`

2022-07-13 20:25 UTC, h5law commented on src/db/helpers.js
> +      return await cancelOrder(user_id, order_id);
Remember the user_id here is the vendor's id so we need to pass `buyer_id` instead to `cancelOrder`

2022-07-13 20:25 UTC, h5law commented on src/db/helpers.js
> +      [order_id, product_id, status]
Again here it helps readability if the parameters are passed in order they appear

2022-07-13 20:25 UTC, h5law commented on src/db/helpers.js
> +          [user_id, order_id, status]
Again reorder these

2022-07-13 20:25 UTC, h5law commented on src/db/helpers.js
> +    if (orders_products.filter(product=> product.status === 'shipped' || product.status === 'disputed').length === orders_products.length) {
`.filter(p => p.status === status)` is what you are looking for

2022-07-13 21:45 UTC, Raphael-hub commented on src/db/helpers.js
> +    }
` const product = await getProductById(product_id);
    const order = await getOrderById(order_id);
    if (!product.user_id === order.user_id) {
      throw new Error('Product doesn\'t belong to user') 
    }`

2022-07-13 21:47 UTC, Raphael-hub commented on src/db/helpers.js
> +    }
```javascript
 const product = await getProductById(product_id);
    const order = await getOrderById(order_id);
    if (!product.user_id === order.user_id) {
      throw new Error('Product doesn\'t belong to user') 
    }
```

2022-07-13 21:47 UTC, Raphael-hub commented on src/db/helpers.js
> +    }
something like this?

2022-07-13 22:11 UTC, Raphael-hub commented on src/db/helpers.js
>      }
```javascript
 const OrdersProducts = await getOrderProductsFromOrder(user_id, order_id);
     if ( !OrdersProducts.products.every(p => p.user_id === user_id)) {
       throw new Error('Not every product in order belongs to vendor');
     }
```

2022-07-14 15:22 UTC, h5law requested changes

2022-07-14 15:22 UTC, h5law commented on src/routes/orders.js
> +  const status = req.body;
The body would contain something like `{ "status": "shipped" }` so we want to do `const { status } = req.body` to extract that from the body

2022-07-14 15:22 UTC, h5law commented on src/routes/orders.js
> +  const status = req.body;
Same again here `{ status }`

2022-07-14 15:22 UTC, h5law commented on src/routes/orders.js
> +router.put('/:order_id/:product_id', isLoggedIn, async (req, res, next) => {
We can use the `checkUserOwnsProduct` middleware from `utils/userOwns.js` here which will extract the `product_id` from `req.params` and if the `req,user.id` matches the products `user_id` then it will attach the product to `res.locals.product` and we could then use `res.locals.product.id` instead of `product_id` as an argument for the function. If they don't own it, it will throw an error which helps

2022-07-14 20:48 UTC, h5law commented on src/routes/orders.js
> +const _ = require('lodash');
Does this import need to be there, it is not used anywhere in the file from what I can see.

2022-07-14 20:53 UTC, h5law approved these changes
Great job on implementing this stuff! It all looks great, merging now.

2022-07-14 20:53 UTC, merged